//
//  LogCategory+Extensions.swift
//  Scribe
//
//  Created by Kai Azim on 2026-01-17.
//

import Scribe

extension LogCategory {
    static let test = LogCategory("TestCategory")

    static let testAllowed = LogCategory("AllowedCategory")
    static let testBlocked = LogCategory("BlockedCategory")

    static let evictOneAuto = LogCategory("Auto/EvictOne.swift", isAutoGenerated: true)
    static let evictTwoAuto = LogCategory("Auto/EvictTwo.swift", isAutoGenerated: true)
    static let evictThreeAuto = LogCategory("Auto/EvictThree.swift", isAutoGenerated: true)

    static let passedInCategory = LogCategory("PassedInCategory")
}
